
version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d # sites-enabled
      - ../..:/var/www/project # root folder
    ports:
      - "8080:80"
    links:
      - php-fpm

  php-fpm:
    # cap_add and security_opt flags are required for core debugging
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp:unconfined"
    build: .
    container_name: php-fpm
    volumes:
      - ../..:/var/www/project # root folder
      - ./php-fpm:/usr/local/etc/php/conf.d.user
      - ../../.composer:/root/composer
      - ../../../packages:/var/www/packages
    environment:
      IN_DOCKER: 1
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_HOME: /root/composer
      PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d:/usr/local/etc/php/conf.d.user
